sudo: false
bundler_args: --jobs=3 --retry=3
cache:
  directories:
    - vendor/bundle
    - ${HOME}/mongodb
before_install:
  - gem update --remote bundler
gemfile:
  - gemfiles/mongoid4.gemfile
  - gemfiles/mongoid5.gemfile
env:
  matrix:
    - MONGODB_VERSION=3.0.12 CONFIG="${TRAVIS_BUILD_DIR}/configs/mongodb-wiredtiger.conf"
    - MONGODB_VERSION=3.0.12 CONFIG="${TRAVIS_BUILD_DIR}/configs/mongodb-mmapv1.conf"
before_script:
  - cd "${TRAVIS_BUILD_DIR}" && ./sh/travis-before_script-mongodb.sh
language: ruby
rvm:
  - 2.1
  - 2.2
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script:
  - bundle exec rake
  - bundle exec rubocop
