cache:
  - bundler
  - apt
before_install:
  - gem update --remote bundler
  # install the latest stable version of MongoDB
  - 'sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10'
  - 'echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list'
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org
language: ruby
rvm:
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2
  fast_finish: true
install:
  - bundle install --retry=3
script:
  - bundle exec rake
  - bundle exec rubocop
