sudo: false
bundler_args: --jobs=3 --retry=3
cache:
  - bundler
before_install:
  - gem update --remote bundler
gemfile:
  - gemfiles/mongoid4.gemfile
  - gemfiles/mongoid5.gemfile
env:
  matrix:
    - MONGODB=3.0.3 CONFIG="--config /tmp/mongodb-wiredtiger.conf"
    - MONGODB=3.0.3 CONFIG=""
before_script:
  - cp configs/mongodb-wiredtiger.conf /tmp/mongodb-wiredtiger.conf
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 $CONFIG &> /dev/null &
language: ruby
rvm:
  - 2.1
  - 2.2
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script:
  - bundle exec rake
  - bundle exec rubocop
