sudo: false
cache: bundler
language: ruby
rvm:
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
  - rbx-2
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: rbx-2
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake
  - bundle exec rubocop
